// Mocks generated by Mockito 5.4.6 from annotations
// in mercado_facil/test/unit/services/produtos_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mercado_facil/data/models/produto.dart' as _i4;
import 'package:mercado_facil/data/services/firestore_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i2.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Produto>> getProdutos() =>
      (super.noSuchMethod(
            Invocation.method(#getProdutos, []),
            returnValue: _i3.Future<List<_i4.Produto>>.value(<_i4.Produto>[]),
          )
          as _i3.Future<List<_i4.Produto>>);

  @override
  _i3.Future<List<_i4.Produto>> getProdutosPorCategoria(String? categoria) =>
      (super.noSuchMethod(
            Invocation.method(#getProdutosPorCategoria, [categoria]),
            returnValue: _i3.Future<List<_i4.Produto>>.value(<_i4.Produto>[]),
          )
          as _i3.Future<List<_i4.Produto>>);

  @override
  _i3.Future<List<_i4.Produto>> getProdutosDestaque() =>
      (super.noSuchMethod(
            Invocation.method(#getProdutosDestaque, []),
            returnValue: _i3.Future<List<_i4.Produto>>.value(<_i4.Produto>[]),
          )
          as _i3.Future<List<_i4.Produto>>);

  @override
  _i3.Future<void> adicionarProduto(Map<String, dynamic>? produto) =>
      (super.noSuchMethod(
            Invocation.method(#adicionarProduto, [produto]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> limparProdutos() =>
      (super.noSuchMethod(
            Invocation.method(#limparProdutos, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Produto>> getProdutosPaginados({
    required int? page,
    int? pageSize = 8,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProdutosPaginados, [], {
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i3.Future<List<_i4.Produto>>.value(<_i4.Produto>[]),
          )
          as _i3.Future<List<_i4.Produto>>);

  @override
  _i3.Future<void> salvarUsuario(String? userId, Map<String, dynamic>? dados) =>
      (super.noSuchMethod(
            Invocation.method(#salvarUsuario, [userId, dados]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getUsuario(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUsuario, [userId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> adicionarFavorito(String? userId, String? produtoId) =>
      (super.noSuchMethod(
            Invocation.method(#adicionarFavorito, [userId, produtoId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removerFavorito(String? userId, String? produtoId) =>
      (super.noSuchMethod(
            Invocation.method(#removerFavorito, [userId, produtoId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isFavorito(String? userId, String? produtoId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorito, [userId, produtoId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<String>> getFavoritos(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoritos, [userId]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<String> criarPedido(
    String? userId,
    Map<String, dynamic>? dadosPedido,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#criarPedido, [userId, dadosPedido]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#criarPedido, [userId, dadosPedido]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getPedidosUsuario(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPedidosUsuario, [userId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> atualizarStatusPedido(String? pedidoId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#atualizarStatusPedido, [pedidoId, status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Produto>> getProdutosComFavoritos(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProdutosComFavoritos, [userId]),
            returnValue: _i3.Future<List<_i4.Produto>>.value(<_i4.Produto>[]),
          )
          as _i3.Future<List<_i4.Produto>>);

  @override
  _i3.Future<List<String>> getCategorias() =>
      (super.noSuchMethod(
            Invocation.method(#getCategorias, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);
}
